In [1]:
import pandas as pd

In [21]:
fd_001 = pd.read_csv('../data/CMAPSSData/train_FD001.txt', sep=r'\s+', header=None)

In [3]:
fd_001.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [8]:
fd_001.shape

(20631, 26)

In [5]:
cols = ['engine_id', 'time'] + [f'operating_setting_{i}' for i in range(1, 4)] + [f'sensor_{i}' for i in range(1, 22)]
fd_001.columns = cols

In [13]:
fd_001

,engine_id,time,operating_setting_1,operating_setting_2,operating_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

In [21]:
fd_001.groupby('engine_id').agg({'time': 'max'}).reset_index()

    engine_id  time
0           1   192
1           2   287
2           3   179
3           4   189
4           5   269
..        ...   ...
95         96   336
96         97   202
97         98   156
98         99   185
99        100   200

[100 rows x 2 columns]

In [7]:
fd_001['sensor_1'].unique()
fd_001['operating_setting_3'].unique()

array([100.])

In [9]:
for col in fd_001.columns:
    print(f'{col}: {fd_001[col].nunique()}')

engine_id: 100
time: 362
operating_setting_1: 158
operating_setting_2: 13
operating_setting_3: 1
sensor_1: 1
sensor_2: 310
sensor_3: 3012
sensor_4: 4051
sensor_5: 1
sensor_6: 2
sensor_7: 513
sensor_8: 53
sensor_9: 6403
sensor_10: 1
sensor_11: 159
sensor_12: 427
sensor_13: 56
sensor_14: 6078
sensor_15: 1918
sensor_16: 1
sensor_17: 13
sensor_18: 1
sensor_19: 1
sensor_20: 120
sensor_21: 4745

In [15]:
nunique = fd_001.nunique()
print(type(nunique))

<class 'pandas.Series'>

#so each panda series is a column in the dataframe and the nunique method returns a series where the index is the column name and the value is the number of unique values in that column.

In [17]:
nunique[nunique == 1]

operating_setting_3    1
sensor_1               1
sensor_5               1
sensor_10              1
sensor_16              1
sensor_18              1
sensor_19              1
dtype: int64

In [20]:
import os
os.getcwd()

'/Users/arghya/Documents/Personal Projects/capital-management-model/notebooks'