In [7]:
import pandas as pd

In [8]:
fd_001 = pd.read_csv('../data/CMAPSSData/train_FD001.txt', sep=r'\s+', header=None)

In [9]:
fd_001.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [10]:
fd_001.shape

(20631, 26)

In [11]:
cols = ['engine_id', 'time'] + [f'operating_setting_{i}' for i in range(1, 4)] + [f'sensor_{i}' for i in range(1, 22)]
fd_001.columns = cols

In [12]:
fd_001

,engine_id,time,operating_setting_1,operating_setting_2,operating_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

In [13]:
fd_001.groupby('engine_id').agg({'time': 'max'}).reset_index()

    engine_id  time
0           1   192
1           2   287
2           3   179
3           4   189
4           5   269
..        ...   ...
95         96   336
96         97   202
97         98   156
98         99   185
99        100   200

[100 rows x 2 columns]

In [14]:
fd_001['sensor_1'].unique()
fd_001['operating_setting_3'].unique()

array([100.])

In [15]:
for col in fd_001.columns:
    print(f'{col}: {fd_001[col].nunique()}')

engine_id: 100
time: 362
operating_setting_1: 158
operating_setting_2: 13
operating_setting_3: 1
sensor_1: 1
sensor_2: 310
sensor_3: 3012
sensor_4: 4051
sensor_5: 1
sensor_6: 2
sensor_7: 513
sensor_8: 53
sensor_9: 6403
sensor_10: 1
sensor_11: 159
sensor_12: 427
sensor_13: 56
sensor_14: 6078
sensor_15: 1918
sensor_16: 1
sensor_17: 13
sensor_18: 1
sensor_19: 1
sensor_20: 120
sensor_21: 4745

In [16]:
nunique = fd_001.nunique()
print(type(nunique))

<class 'pandas.Series'>

#so each panda series is a column in the dataframe and the nunique method returns a series where the index is the column name and the value is the number of unique values in that column.

In [17]:
nunique[nunique == 1]

operating_setting_3    1
sensor_1               1
sensor_5               1
sensor_10              1
sensor_16              1
sensor_18              1
sensor_19              1
dtype: int64

In [18]:
import os
os.getcwd()

'/Users/arghya/Documents/Personal Projects/capital-management-model/notebooks'

In [19]:
import pandas as pd

fd_001_processed = pd.read_csv('../data/processed/FD001_processed.csv')
fd_001_processed.head()
fd_001_processed.describe()

,engine_id,time,operating_setting_1,operating_setting_2,sensor_2,sensor_3,sensor_4,sensor_6,sensor_7,sensor_8,sensor_9,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_17,sensor_20,sensor_21,RUL
count,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000
mean,51.506568,108.807862,-0.000009,0.000002,642.680934,1590.523119,1408.933782,21.609803,553.367711,2388.096652,9065.242941,47.541168,521.413470,2388.096152,8143.752722,8.442146,393.210654,38.816271,23.289705,107.807862
std,29.227633,68.880990,0.002187,0.000293,0.500053,6.131150,9.000605,0.001389,0.885092,0.070985,22.082880,0.267087,0.737553,0.071919,19.076176,0.037505,1.548763,0.180746,0.108251,68.880990
min,1.000000,1.000000,-0.008700,-0.000600,641.210000,1571.040000,1382.250000,21.600000,549.850000,2387.900000,9021.730000,46.850000,518.690000,2387.880000,8099.940000,8.324900,388.000000,38.140000,22.894200,0.000000
25%,26.000000,52.000000,-0.001500,-0.000200,642.325000,1586.260000,1402.360000,21.610000,552.810000,2388.050000,9053.100000,47.350000,520.960000,2388.040000,8133.245000,8.414900,392.000000,38.700000,23.221800,51.000000
50%,52.000000,104.000000,0.000000,0.000000,642.640000,1590.100000,1408.040000,21.610000,553.440000,2388.090000,9060.660000,47.510000,521.480000,2388.090000,8140.540000,8.438900,393.000000,38.830000,23.297900,103.000000
75%,77.000000,156.000000,0.001500,0.000300,643.000000,1594.380000,1414.555000,21.610000,554.010000,2388.140000,9069.420000,47.700000,521.950000,2388.140000,8148.310000,8.465600,394.000000,38.950000,23.366800,155.000000
max,100.000000,362.000000,0.008700,0.000600,644.530000,1616.910000,1441.490000,21.610000,556.060000,2388.560000,9244.590000,48.530000,523.380000,2388.560000,8293.720000,8.584800,400.000000,39.430000,23.618400,361.000000

In [22]:
#Linear model
from sklearn.linear_model import LinearRegression
train_df = fd_001_processed
X = train_df.drop(columns=['RUL', 'engine_id'])
Y = train_df['RUL']
lin_reg = LinearRegression()
lin_reg.fit(X, Y)

LinearRegression()

In [23]:
from pathlib import Path   
import sys
sys.path.append('../src')
from etl import load_data

In [24]:
import sys

for p  in sys.path:
    print(p)

/opt/homebrew/Cellar/python@3.13/3.13.4/Frameworks/Python.framework/Versions/3.13/lib/python313.zip
/opt/homebrew/Cellar/python@3.13/3.13.4/Frameworks/Python.framework/Versions/3.13/lib/python3.13
/opt/homebrew/Cellar/python@3.13/3.13.4/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload

/Users/arghya/Documents/Personal Projects/capital-management-model/.venv/lib/python3.13/site-packages
../src

In [25]:
test_path = Path('../data/CMAPSSData/test_FD001.txt')
test_df = load_data(test_path)

In [26]:
test_df.head()

,engine_id,time,operating_setting_1,operating_setting_2,operating_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,521.72,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,522.16,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,521.97,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,521.38,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,522.15,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130

In [27]:
feature_cols = train_df.columns

In [28]:
test_df = test_df[feature_cols[:len(feature_cols)-1]]
test_df.head()

,engine_id,time,operating_setting_1,operating_setting_2,sensor_2,sensor_3,sensor_4,sensor_6,sensor_7,sensor_8,sensor_9,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_17,sensor_20,sensor_21
0,1,1,0.0023,0.0003,643.02,1585.29,1398.21,21.61,553.90,2388.04,9050.17,47.20,521.72,2388.03,8125.55,8.4052,392,38.86,23.3735
1,1,2,-0.0027,-0.0003,641.71,1588.45,1395.42,21.61,554.85,2388.01,9054.42,47.50,522.16,2388.06,8139.62,8.3803,393,39.02,23.3916
2,1,3,0.0003,0.0001,642.46,1586.94,1401.34,21.61,554.11,2388.05,9056.96,47.50,521.97,2388.03,8130.10,8.4441,393,39.08,23.4166
3,1,4,0.0042,0.0000,642.44,1584.12,1406.42,21.61,554.07,2388.03,9045.29,47.28,521.38,2388.05,8132.90,8.3917,391,39.00,23.3737
4,1,5,0.0014,0.0000,642.51,1587.19,1401.92,21.61,554.16,2388.01,9044.55,47.31,522.15,2388.03,8129.54,8.4031,390,38.99,23.4130

In [29]:
assert test_df.columns.tolist() == train_df.columns[:len(train_df.columns)-1].tolist()

In [30]:
test_df.columns.tolist() == train_df.columns[:len(train_df.columns)-1].tolist()

True

In [31]:
for_prediction = test_df.groupby('engine_id').agg({'time' : 'max'}).reset_index()
for_prediction.head()

   engine_id  time
0          1    31
1          2    49
2          3   126
3          4   106
4          5    98

In [32]:
test_df.groupby('engine_id')['time'].transform("max")
test_df['last_time'] = test_df.groupby('engine_id')['time'].transform("max")
test_df = test_df[test_df['time'] == test_df['last_time']].drop(columns=['last_time', 'engine_id'])
test_df.head()

,time,operating_setting_1,operating_setting_2,sensor_2,sensor_3,sensor_4,sensor_6,sensor_7,sensor_8,sensor_9,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_17,sensor_20,sensor_21
30,31,-0.0006,0.0004,642.58,1581.22,1398.91,21.61,554.42,2388.08,9056.40,47.23,521.79,2388.06,8130.11,8.4024,393,38.81,23.3552
79,49,0.0018,-0.0001,642.55,1586.59,1410.83,21.61,553.52,2388.10,9044.77,47.67,521.74,2388.09,8126.90,8.4505,391,38.81,23.2618
205,126,-0.0016,0.0004,642.88,1589.75,1418.89,21.61,552.59,2388.16,9049.26,47.88,520.83,2388.14,8131.46,8.4119,395,38.93,23.2740
311,106,0.0012,0.0004,642.78,1594.53,1406.88,21.61,552.64,2388.13,9051.30,47.65,521.88,2388.11,8133.64,8.4634,395,38.58,23.2581
409,98,-0.0013,-0.0004,642.27,1589.94,1419.36,21.61,553.29,2388.10,9053.99,47.46,521.00,2388.15,8125.74,8.4362,394,38.75,23.4117

In [33]:
predictions = lin_reg.predict(test_df)
predictions

array([170.80879525, 138.04890363,  84.97907873, 102.02263224,
       113.25074231, 113.87725056, 103.18091338,  74.56724149,
       131.76518741,  80.53088358, 108.99944154,  70.91422286,
        69.32535166, 133.44026928, 152.06423839, 125.32579944,
        73.34271862,  79.42330893, 107.30006038,  23.63803382,
       102.47697704, 154.21289528, 129.11919926,  36.68927983,
       148.67838975, 146.38462599, 107.22178601,  88.39847536,
        93.7378351 ,  87.46500199,  13.59668468,  94.94524785,
       130.56069196,   3.55990991,   2.37088315,  54.99212161,
        82.63657802,  76.25253208, 170.11068443,  53.74616072,
        88.81775667,  41.41713865,  65.24487342, 135.21009033,
        75.21072615,  67.8912695 , 128.19107804, 124.61168466,
       -24.90944282, 134.37339691, 100.36522674,  43.60286188,
        50.10600314, 141.88156468, 126.52204008,  47.38195326,
        84.53776776,  53.97317124, 149.74370432,  96.62678108,
        53.76220029,  48.57899794,  69.88373073,  56.10772508,
       169.39779382,  30.83441972, 145.25541908,  16.94998182,
       142.63024249,  89.53492946, 146.00706118,  91.71384754,
       139.26336111,  92.27607738, 139.27900905,   0.573646  ,
        54.91491724, 174.57193769, 114.37488617,  90.66307752,
        -1.8291339 ,  23.4574841 , 137.66048144,  60.72921528,
       142.29073109, 108.77686565, 159.26487271, 138.3739877 ,
        82.17893806,  54.37051132,  18.73494007,  40.27004245,
        25.18227046,  72.77821467, 139.11600254, 150.9387588 ,
       100.65386694,  96.95530148, 148.18450686,  16.323466  ])

In [34]:
assert len(predictions) == len(test_df)

In [35]:
print(len(predictions), len(test_df))

100 100

In [36]:
import numpy as np
true_rul = pd.read_csv('../data/CMAPSSData/RUL_FD001.txt', sep=r'\s+', header=None)
true_rul = np.array(true_rul[0])

In [37]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

mse = mean_squared_error(true_rul, predictions)
print(f'Root Mean Squared Error: {mse ** 0.5}')
mae = mean_absolute_error(true_rul, predictions)
print(f'Mean Absolute Error: {mae}')

Root Mean Squared Error: 31.2504741176447
Mean Absolute Error: 25.975172458163435

Lin reg performs poorly. Could be because
1. Engine degradation is not linear (i.e. sensor value changes don't always lead to changes like in the coefficients. There might be dependency between the sensors, plus you would expect changes in temp to indicate different things for an engine that has run for 100 cycles vs. 20 cycles.)
2. Could be that different sensor measurements together say something too as in temp high, pressure low = near failure. Lin reg can't capture that properly. Decision tree would be better at this, as it can literally do if x > 100, y < 20, we close to failure. 
3. We're only using the current snapshot for prediction i.e. the last cycle measurement. You would expect prev cycles to contain info about the degradation too!

In [73]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(max_depth=5, random_state=42) #max_depth prevents overfitting (otherwise tree can grow too deep and memorize the training data), random state ensures reproducibility

In [74]:
tree_reg.fit(X, Y)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [75]:
d_tree_preds = tree_reg.predict(test_df)
d_tree_preds

array([165.90877193, 143.74634146,  45.51013514,  72.34305151,
        83.68837675,  83.68837675, 108.84340659,  83.68837675,
       143.74634146, 108.84340659, 104.56221198, 108.84340659,
        83.68837675, 152.18957346, 146.72238806, 126.56658185,
        75.14590747,  72.34305151, 111.75476839,  28.17731421,
        75.14590747, 152.18957346, 126.56658185,  23.33928571,
       150.02745995, 122.43806104, 108.84340659, 108.84340659,
       111.75476839,  83.68837675,  40.90909091,  46.72      ,
       143.74634146,   9.18148148,   9.18148148,  28.17731421,
        49.9945593 ,  28.17731421, 182.82177264,  21.61384615,
        83.68837675,  21.61384615,  83.68837675, 143.74634146,
        83.68837675,  40.90909091, 104.56221198, 122.43806104,
         9.18148148, 122.43806104,  83.68837675,  28.03658537,
        40.90909091, 126.56658185, 108.84340659,  28.17731421,
        83.68837675,  72.34305151, 127.16730038, 108.84340659,
        72.34305151,  46.72      ,  72.34305151,  72.34305151,
       164.40967283,  21.61384615, 150.02745995,   9.18148148,
       164.40967283,  72.34305151, 150.02745995,  72.34305151,
       126.56658185,  83.68837675, 104.56221198,  28.17731421,
        49.9945593 , 146.72238806,  72.34305151,  83.68837675,
         9.18148148,   9.18148148, 127.16730038,  83.68837675,
       165.9       ,  83.68837675, 143.74634146, 128.96763203,
       111.75476839,  28.17731421,  28.17731421,  28.17731421,
        49.9945593 ,  49.9945593 , 122.43806104, 126.56658185,
       111.75476839,  72.34305151, 126.56658185,  23.33928571])

In [76]:
d_tree_mse = mean_squared_error(true_rul, d_tree_preds)
print(f'Decision Tree Root Mean Squared Error: {d_tree_mse ** 0.5}')
d_tree_mae = mean_absolute_error(true_rul, d_tree_preds)
print(f'Decision Tree Mean Absolute Error: {d_tree_mae}')

Decision Tree Root Mean Squared Error: 27.056615144112186
Decision Tree Mean Absolute Error: 21.466724805956577

random forest doesn't seem to work much better either. Could be because
1. Most of the data is actually linear. this is failure mode 1, so we expect data to be simple..
2. We are not using the whole trajectory, means that each model only has information about last cycle, might not be enough for both lin reg and dtree reg. 
3. Underfitting doesn't seem to be issue. Increasing tree depth made the error worse. 
4. Maybe need to use many trees

In [95]:
from sklearn.ensemble import RandomForestRegressor

rf_reg = RandomForestRegressor(n_estimators=100, max_depth=8, random_state=42) #n_estimators is the number of trees in the forest

#n_estimators = number of trees in the forest, max_depth = maximum depth of each tree, random_state = seed for reproducibility
#more estimators = more trees = better performance but slower training and prediction time, max_depth = bias variance trade off, deeper trees = lower bias but higher variance, shallower trees = higher bias but lower variance

In [96]:
rf_reg.fit(X, Y)

RandomForestRegressor(max_depth=8, random_state=42)

In [97]:
rf_preds = rf_reg.predict(test_df)

In [98]:
rf_reg_mse = mean_squared_error(true_rul, rf_preds)
print(f'Random Forest Root Mean Squared Error: {rf_reg_mse ** 0.5}')

Random Forest Root Mean Squared Error: 25.184938480781053

In [99]:
rf_reg_mae = mean_absolute_error(true_rul, rf_preds)
print(f'Random Forest Mean Absolute Error: {rf_reg_mae}')

Random Forest Mean Absolute Error: 19.122982875965423

#RF seems to do slightly better, but not that much better. I think the problem is that we're using a snapshot of the last cycle rather than giving it all the data of the trajectory. i.e. non-linearity doesn't seem to be the only challenge.